name: Print Success Message

on:
  push:
    branches:
      - develop

jobs:
  print_success_message:
    runs-on: ubuntu-latest

    steps:
      - name: Print success message
        run: |
          echo "GitHub Actions successfully completed!"
